language: csharp
mono: none
# Need explicit dotnet version otherwise OSX fails to download/install dotnet
dotnet: 2.1.403

os:
  - linux
  - osx
sudo: required
services:
  - docker

# At least one script line is required:
# https://docs.travis-ci.com/user/languages/csharp/#net-core
script:
  - dotnet restore
  - dotnet build
  - dotnet test --filter "platform!=windows" --verbosity normal tests

after_success:
  - ./scripts/qemu_arm64.sh