language: csharp
mono: none
dotnet: 2.1.403

os:
  - linux
  - osx
sudo: false

# At least one script line is required:
# https://docs.travis-ci.com/user/languages/csharp/#net-core
script:
  - dotnet restore
  - dotnet test --filter "platform!=windows" tests