image: 
- Visual Studio 2017
- Ubuntu
configuration:
  - Debug
  - Release

before_build:
  - dotnet restore
  - cmd: choco install opencover.portable
  - cmd: choco install codecov

build:
  verbosity: minimal

test_script:
  - cmd: OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test --filter platform!=posix" -output:".\coverage.xml" -oldstyle
  - sh: dotnet test --filter "platform!=windows"

after_test:
  - cmd: codecov -f "coverage.xml" -t 2a07cd3d-8620-4495-8c14-3252b10b90bd
